In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [4]:
%matplotlib inline

In [6]:
df=pd.read_csv(r"C:\Users\bottle.csv")

In [7]:
df.head()

Cst_Cnt  Btl_Cnt       Sta_ID                                Depth_ID  \
0        1        1  054.0 056.0  19-4903CR-HY-060-0930-05400560-0000A-3   
1        1        2  054.0 056.0  19-4903CR-HY-060-0930-05400560-0008A-3   
2        1        3  054.0 056.0  19-4903CR-HY-060-0930-05400560-0010A-7   
3        1        4  054.0 056.0  19-4903CR-HY-060-0930-05400560-0019A-3   
4        1        5  054.0 056.0  19-4903CR-HY-060-0930-05400560-0020A-7   

   Depthm  T_degC  Salnty  O2ml_L  STheta  O2Sat  ...  R_PHAEO  R_PRES  \
0       0   10.50  33.440     NaN  25.649    NaN  ...      NaN       0   
1       8   10.46  33.440     NaN  25.656    NaN  ...      NaN       8   
2      10   10.46  33.437     NaN  25.654    NaN  ...      NaN      10   
3      19   10.45  33.420     NaN  25.643    NaN  ...      NaN      19   
4      20   10.45  33.421     NaN  25.643    NaN  ...      NaN      20   

   R_SAMP  DIC1  DIC2  TA1  TA2  pH2  pH1  DIC Quality Comment  
0     NaN   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  
1     NaN   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  
2     NaN   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  
3     NaN   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  
4     NaN   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  

[5 rows x 74 columns]

In [9]:
#we are considering only the temperature and the salinity of the water or the dependence of temperature on salinity
#we need to drop the other colunms

In [16]:
df.count(axis=1)

0         33
1         33
2         33
3         33
4         33
5         33
6         33
7         33
8         33
9         33
10        33
11        33
12        33
13        33
14        33
15        33
16        33
17        29
18        33
19        33
20        33
21        33
22        33
23        33
24        33
25        33
26        33
27        33
28        33
29        33
          ..
864833    47
864834    47
864835    47
864836    47
864837    47
864838    47
864839    47
864840    47
864841    46
864842    45
864843    45
864844    45
864845    47
864846    46
864847    46
864848    44
864849    45
864850    44
864851    45
864852    44
864853    44
864854    45
864855    44
864856    45
864857    44
864858    42
864859    45
864860    45
864861    44
864862    44
Length: 864863, dtype: int64

In [24]:
df.drop([['Cst_Cnt', 'Btl_Cnt', 'Sta_ID', 'Depth_ID', 'Depthm', 'O2ml_L', 'STheta', 'O2Sat', 'Oxy_µmol/Kg', 'BtlNum',
       'RecInd', 'T_prec', 'T_qual', 'S_prec', 'S_qual', 'P_qual', 'O_qual',
       'SThtaq', 'O2Satq', 'ChlorA', 'Chlqua', 'Phaeop', 'Phaqua', 'PO4uM',
       'PO4q', 'SiO3uM', 'SiO3qu', 'NO2uM', 'NO2q', 'NO3uM', 'NO3q', 'NH3uM',
       'NH3q', 'C14As1', 'C14A1p', 'C14A1q', 'C14As2', 'C14A2p', 'C14A2q',
       'DarkAs', 'DarkAp', 'DarkAq', 'MeanAs', 'MeanAp', 'MeanAq', 'IncTim',
       'LightP', 'R_Depth', 'R_TEMP', 'R_POTEMP', 'R_SALINITY', 'R_SIGMA',
       'R_SVA', 'R_DYNHT', 'R_O2', 'R_O2Sat', 'R_SIO3', 'R_PO4', 'R_NO3',
       'R_NO2', 'R_NH4', 'R_CHLA', 'R_PHAEO', 'R_PRES', 'R_SAMP', 'DIC1',
       'DIC2', 'TA1', 'TA2', 'pH2', 'pH1', 'DIC Quality Comment']],axis=1,inplace =True
)
df

T_degC   Salnty
0       10.500  33.4400
1       10.460  33.4400
2       10.460  33.4370
3       10.450  33.4200
4       10.450  33.4210
5       10.450  33.4310
6       10.450  33.4400
7       10.240  33.4240
8       10.060  33.4200
9        9.860  33.4940
10       9.830  33.5100
11       9.670  33.5800
12       9.500  33.6400
13       9.320  33.6890
14       8.760  33.8470
15       8.710  33.8600
16       8.530  33.8760
17       8.450      NaN
18       8.260  33.9260
19       7.960  33.9800
20       7.770  33.9900
21       6.800  34.0400
22       6.550  34.0560
23       5.780  34.1130
24       5.300  34.1600
25       5.290  34.1610
26       5.010  34.2100
27       4.720  34.2610
28       4.440  34.3100
29      10.100  32.9500
...        ...      ...
864833  19.566  33.2900
864834  19.572  33.3035
864835  19.120  33.4630
864836  19.024  33.4556
864837  17.808  33.3900
864838  16.877  33.3576
864839  16.911  33.3498
864840  16.374  33.4218
864841  15.747  33.5797
864842  14.747  33.4892
864843  13.845  33.5379
864844  12.096  33.4594
864845  11.888  33.4133
864846  10.071  33.3965
864847   9.288  33.6306
864848   8.889  33.8506
864849   8.601  33.9349
864850   8.325  33.9819
864851   7.831  34.0234
864852   7.538  34.0420
864853   6.943  34.1104
864854   6.694  34.1101
864855   6.312  34.1563
864856   5.993  34.2160
864857   5.818  34.2382
864858  18.744  33.4083
864859  18.744  33.4083
864860  18.692  33.4150
864861  18.161  33.4062
864862  17.533  33.3880

[864863 rows x 2 columns]

In [25]:
df.columns

Index(['T_degC', 'Salnty'], dtype='object')

In [72]:
X=df[["T_degC"]]

In [73]:
X.count()

T_degC    853900
dtype: int64

In [74]:
Y=df[["Salnty"]]

In [75]:
Y.count()

Salnty    817509
dtype: int64

In [76]:
X.isnull().sum()

T_degC    10963
dtype: int64

In [77]:
Y.isnull().sum()

Salnty    47354
dtype: int64

In [78]:
#therefore from the above data it is very clear that there are many null values in the data set,these outliers are the probelm for the data

In [84]:
X.fillna(0,inplace=True)

In [83]:
X.isnull().sum()

T_degC    0
dtype: int64

In [ ]:
#clearly there are no null values now in the X dataframe 

In [86]:
Y.fillna(0,inplace=True)
Y.isnull().sum()


Salnty    0
dtype: int64

In [87]:
Y.isnull().sum()

Salnty    0
dtype: int64

In [88]:
Y.notna().sum()

Salnty    864863
dtype: int64

In [89]:
X.notna().sum()

T_degC    864863
dtype: int64

In [62]:
reg= LinearRegression()


In [90]:
reg.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [64]:
X.count()

T_degC    864863
dtype: int64

In [91]:
Y.count()

Salnty    864863
dtype: int64

In [93]:
reg.coef_

array([[0.20860709]])

In [95]:
reg.intercept_

array([29.76315191])

In [97]:
#the temperature if the salinity is 10000
reg.predict([[10000]])

array([[2115.83405963]])